development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: josephspatt@gmail.com
  :password: cracked2336
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: josephspatt@gmail.com
  :password: cracked2336
  :enable_starttls_auto: true